name: eatshots_video_player
description: "A high-performance, Reels-style short-form video player plugin for Flutter, optimized with aggressive caching, background prefetching, and native controller pooling."
version: 0.1.8
homepage: https://github.com/Narukarudra10/eatshots_video_player
repository: https://github.com/Narukarudra10/eatshots_video_player

environment:
  sdk: ^3.12.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.eatshots_video_player
        pluginClass: EatshotsVideoPlayerPlugin
      ios:
        pluginClass: EatshotsVideoPlayerPlugin
      macos:
        pluginClass: EatshotsVideoPlayerPlugin
