name: eatshots_video_player
description: "DEPRECATED: This package has been renamed to video_view_player. Please migrate to video_view_player."
version: 0.2.4
homepage: https://github.com/Narukarudra10/eatshots_video_player
repository: https://github.com/Narukarudra10/eatshots_video_player

environment:
  sdk: ^3.12.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  video_view_player: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
